// Generated by ts-to-zod
import { z } from "zod";

export const lobbySettingsSchema = z.object({
    id: z.string()
});

export const lobbySchema = z.object({
    id: z.number().optional(),
    status: z.string(),
    settings: lobbySettingsSchema
});
